### ISSUE TITLE
Searcher

### ISSUE THREAD

**Issue by iamrecursion** [luna/enso#720]
### Summary
The searcher is one of the most important parts of the Enso user experience, providing users with intelligent autcomplete and context-aware suggestions, as well as examples and documentation all in one place. Without it, we severely compromise the IDE's UX, and hence we need to get it implemented. 

### Value
The IDE will be able to support the searcher properly.

### Specification

- [ ] Design the searcher (#442).
- [ ] Implement runtime support for the searcher (#404). 
- [ ] Implement language server support for the searcher (#403). 

### Acceptance Criteria & Test Cases

- The above specification has been completed.
- The above tasks are ready to be integrated with the IDE.
- The engine protocol specification is up to date with respect to any changes.
