### ISSUE TITLE
Undo/Redo

### ISSUE THREAD

**Issue by iamrecursion** [luna/enso#722]
### Summary
The nature of the Enso Engine as a multi-client service implies that Undo and Redo must be mediated by the service so as to keep a coherent stream of edits for multiple users. To that end, we need to design and implement this functionality into the language server. 

### Value
The IDE will be able to support coherent and mediated undo/redo for users. 

### Specification

- [ ] Design undo and redo (#551).
- [ ] Implement the undo functionality (#552).
- [ ] Implement the redo functionality (#553).

### Acceptance Criteria & Test Cases

- We have working undo/redo functionality.
- All changes to the protocol have been recorded in the enso protocol design document.
