### ISSUE TITLE
Enso Beta Compiler Improvements

### ISSUE THREAD

**Issue by iamrecursion** [luna/enso#839]
### Summary
With the parser improved dramatically, it's time to return to improving the compiler and the syntactic support alongside it. 

### Value
The compiler can better support the full-blooded vision of Enso, the language.

### Specification
Each of the following steps should land on master with the compiler in a working state. 

- [ ] Handle access modifiers properly (#774).
- [ ] Handle pattern matching function definitions (#759). 
- [ ] Handle naming properly (#757).
- [ ] Handle cyclic imports (#787). 
- [ ] Remove the need for explicit `.call` (#693).
- [ ] Handle assignment modes properly (#756). 
- [ ] Handle reserved names properly (#730). 
- [ ] Handle operator `.` properly (#729). 
- [ ] Handle suspended blocks properly (#760).
- [ ] Runtime support for warnings (#689).
- [ ] Fix syntax-related crashes (#798).

### Acceptance Criteria & Test Cases

- The above-listed specification points have been completed and have all landed on master.
- They are accompanied by rigorous tests and benchmarks to ensure that there are no functionality regressions and that performance is acceptable.
